name: Release Docker image

on:
  release:
    types: [published]   # 当新 release 发布时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 拉取源码
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: 获取 release 版本号
      - name: Get release version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      # Step 4: 构建并 push 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            531144129/astrm:latest
            531144129/astrm:${{ steps.get_version.outputs.version }}
